FROM debian:bookworm
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl php-common php-fpm php-curl php-mysql \
    php-gd php-mbstring php-zip php-xml php-ctype vim-tiny cron \
    supervisor openssl git nginx mariadb-server mariadb-client && \
    useradd -r wavelog && \
    mkdir /run/mysqld && chown mysql:mysql /run/mysqld && \
    rm -f /etc/php/8.2/fpm/pool.d/www.conf /etc/nginx/sites-enabled/default && \
    git clone https://github.com/wavelog/wavelog /app && \
    mkdir /app/application/config/docker && \
    chown -R wavelog:wavelog /app && \
    sed -i "s/\$config\['index_page'\] = 'index.php';/\$config\['index_page'\] = '';/g" /app/install/config/config.php && \
    echo "* * * * * wavelog curl --silent http://localhost/cron/run &>/dev/null" >> /etc/crontab

COPY wavelog-fpm.conf /etc/php/8.2/fpm/pool.d/
COPY wavelog-nginx.conf /etc/nginx/sites-enabled/
COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY --chmod=755 start-wavelog /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/start-wavelog" ]