#!/bin/sh

# if config.php is present, app is already set up
if [ -f /app/application/config/docker/config.php ]; then
    exec /usr/bin/supervisord
fi

# initialize database

mariadb-install-db --user mysql --datadir /var/lib/mysql >/dev/null

if [ -z "$DATABASE_PASSWORD" ]; then
    dbpass=$(openssl rand -hex 16)
    echo "Generated database password: $dbpass"
else
    dbpass="$DATABASE_PASSWORD"
fi

mariadbd --bootstrap <<EOF
CREATE DATABASE wavelog;
CREATE USER wavelog@localhost IDENTIFIED BY '${dbpass}';
GRANT ALL PRIVILEGES ON wavelog.* TO 'wavelog'@'localhost';
FLUSH PRIVILEGES;
EOF

exec /usr/bin/supervisord